### ISSUE TITLE
Add tests for cli

### ISSUE THREAD

**Issue by pke** [wsierakowski/tests2json#1]
I am currently struggling testing my CLI code that also accepts file input as well as piping.
I can't seem to get it work inside tests when I call my CLI script using `exec` and `exceFile`. The `execFile` tests always timeout, cause the CLI code things TTY is not enabled and wants to stream input.
Have you tried adding tests for the CLI yourself?

**Comment by wsierakowski** [comment]
hi @pke, I don't think I managed to test CLI scripts in the way you suggested. When testing scripts I typically aim to test the logic (behavior) and if I can't access external interfaces I tend to use stubs.
If you find a solution to your problem please share it here as well, it may help others who accidentally land here as well.

**Comment by pke** [comment]
Yes, I have solved it indeed after carefully reading the docs. Was 3 day struggle.

One must disable the input stream for the child process. What is not there can not be waited for in the child process ;)

See here: https://github.com/pke/json-mask/blob/feature/add-cli/test/cli-test.js#L49

I specifically wanted to test the complete user experience so I am happy now.

**Comment by wsierakowski** [comment]
Well done, and thanks for sharing this @pke!
